anatomicalTemplate:  /tigress/HANLIU/mridata/CPAC_rawdata/INDI/Retrospective/%s/%s/anat/mprage_1.nii.gz

functionalTemplate:  /tigress/HANLIU/mridata/CPAC_rawdata/INDI/Retrospective/%s/%s/func/rest_*.nii.gz

subjectList:  ["50002"]

subjectListName: ["50002"]

exclusionSubjectList:  None

siteList:  [Pitt]

scanParametersCSV:  scan_parameters_abide.csv

outputSubjectListLocation:  /tigress/HANLIU/mridata/CPAC/subjectlistoutput/

workingDirectory: /tigress/HANLIU/mridata/CPAC_processed/tmp_preprocess/

outputDirectory: /tigress/HANLIU/mridata/CPAC_processed/tmp_finished/

crashLogDirectory: /tigress/HANLIU/mridata/CPAC/crashLog/

pipelineName:  'CPAC_2016-01-22'

removeWorkingDir: False

runRegistrationPreprocessing : [1]
resolution_for_anat : 3mm
template_brain_only_for_anat : /tigress/HANLIU/mridata/CPAC_image_resource/FSL_data/MNI152_T1_${resolution_for_anat}_brain.nii.gz
template_skull_for_anat : /tigress/HANLIU/mridata/CPAC_image_resource/FSL_data/MNI152_T1_${resolution_for_anat}.nii.gz
regOption : ['ANTS']
fnirtConfig : T1_2_MNI152_3mm
ref_mask : /tigress/HANLIU/mridata/CPAC_image_resource/FSL_data/MNI152_T1_${resolution_for_anat}_brain_mask_dil.nii.gz
regWithSkull : [0]

template_symmetric_brain_only : /tigress/HANLIU/mridata/CPAC_image_resource/FSL_data/MNI152_T1_${resolution_for_anat}_brain.nii.gz
template_symmetric_skull : /tigress/HANLIU/mridata/CPAC_image_resource/FSL_data/MNI152_T1_${resolution_for_anat}.nii.gz
dilated_symmetric_brain_mask : /tigress/HANLIU/mridata/CPAC_image_resource/FSL_data/MNI152_T1_${resolution_for_anat}_brain_mask_dil.nii.gz

functionalMasking : ['3dAutoMask']

template_brain_only_for_func : /tigress/HANLIU/mridata/CPAC_image_resource/FSL_data/MNI152_T1_${resolution_for_anat}_brain.nii.gz
template_skull_for_func : /tigress/HANLIU/mridata/CPAC_image_resource/FSL_data/MNI152_T1_${resolution_for_anat}.nii.gz


runSegmentationPreprocessing : [1]
whiteMatterThreshold : [0.98]
grayMatterThreshold : [0.7]
cerebralSpinalFluidThreshold : [0.98]
priors_path : /tigress/HANLIU/mridata/CPAC_image_resource/tissuepriors/${resolution_for_anat}
PRIORS_WHITE : $priors_path/avg152T1_white_bin.nii.gz
PRIORS_GRAY : $priors_path/avg152T1_gray_bin.nii.gz
PRIORS_CSF : $priors_path/avg152T1_csf_bin.nii.gz

startIdx : 0
stopIdx : None
TR : None
slice_timing_correction : [1]
slice_timing_pattern : ['Use NIFTI Header']

runRegisterFuncToAnat : [1]
runBBReg : [0]
boundaryBasedRegistrationSchedule : /tigress/HANLIU/mridata/local/fsl-5.0.8/fsl/etc/flirtsch/bbr.sch
func_reg_input :  ['Mean Functional']
func_reg_input_volume :  0

runRegisterFuncToMNI : [1]
resolution_for_func : 3mm
identityMatrix : /tigress/HANLIU/mridata/local/fsl-5.0.8/fsl/etc/flirtsch/ident.mat

runFristonModel : [1]
runGenerateMotionStatistics : [1]

runScrubbing : [0]
scrubbingThreshold : [0.2]
numRemovePrecedingFrames : 1
numRemoveSubsequentFrames : 2

runNuisance : [1]
lateral_ventricles_mask : /tigress/HANLIU/mridata/CPAC_image_resource/HarvardOxford-lateral-ventricles-thr25-3mm.nii.gz
Corrections :
    - compcor : 1
      wm : 0
      csf : 1
      global : 1
      pc1 : 0
      motion : 1
      linear : 1
      quadratic : 1
      gm : 0
nComponents : [5]

runMedianAngleCorrection : [0]
targetAngleDeg : [90]

runFrequencyFiltering : [1]
nuisanceBandpassFreq : [[0.001, 0.08]]

fwhm : [6]

maskSpecificationFileForSCA : None
runSCA : [0]
runMultRegSCA : [0]
mrsDemean : False
mrsNorm : False

runALFF : [0]
highPassFreqALFF : [0.01]
lowPassFreqALFF : [0.1]

runBASC : [0]
bascROIFile : None
bascTimeseriesBootstraps : 100
bascDatasetBootstraps : 100
bascAffinityThresholdFile :
bascClusters : 6

runReHo : [0]
clusterSize : 7

runNetworkCentrality : [0]
templateSpecificationFile : '/path/to/centrality/specs'
degWeightOptions : [True, True]
degCorrelationThresholdOption : 0
degCorrelationThreshold : 0.001
eigWeightOptions : [False, False]
eigCorrelationThresholdOption : 0
eigCorrelationThreshold : 0.001
lfcdWeightOptions : [True, True]
lfcdCorrelationThresholdOption : 0
lfcdCorrelationThreshold : 0.001
memoryAllocatedForDegreeCentrality : 2.0

runCWAS : [0]
cwasROIFile : '/path/to/cwas_mask_file'
cwasFSamples : 5000
cwasParallelNodes : 10
cwasRegressorFile : '/path/to/cwas_regressor_file'


runROITimeseries : [0]

roiTSOutputs : [False, False]

roiDirectoryPath : '/path/to/roi_definitions_directory'

runVoxelTimeseries : [0]

voxelTSOutputs : [False, False]

maskDirectoryPath : '/path/to/mask_definitions_directory'

runSurfaceRegistraion : [0]

reconSubjectsDirectory : '/path/to/fs_output_directory'

runVerticesTimeSeries : [0]

verticesTSOutputs : [False, False]

seedSpecificationFile : None
runOnGrid : False
numSubjectsAtOnce : 1
num_ants_threads : 1
numCoresPerSubject : 1
already_skullstripped : [0]
reGenerateOutputs : False
runAnatomicalDataGathering : [1]
runFunctionalDataGathering : [1]
runAnatomicalPreprocessing : [1]
runFunctionalPreprocessing : [1]
runVMHC : [0]

runSpatialRegression : [0]
runDualReg : [0]
runZScoring : [0]
generateQualityControlImages : [0]
runSymbolicLinks : [1]
